

export enum CompanySize {
    SMALL = '1-50',
    MEDIUM = '51-200',
    LARGE = '201-500',
    ENTERPRISE = '500+',
}



export enum CompanyStatus {
    PENDING = 'pending',
    ACTIVE = 'active',
    SUSPENDED = 'suspended',
    DELETED = 'deleted',
}


export enum VerificationStatus {
    PENDING = 'pending',
    VERIFIED = 'verified',
    REJECTED = 'rejected',
}


// ─── Labels cho UI ──────────────────────────────────────────────────────────────

export const COMPANY_STATUS_LABELS: Record<CompanyStatus, string> = {
    [CompanyStatus.PENDING]:   'Chờ duyệt',
    [CompanyStatus.ACTIVE]:    'Hoạt động',
    [CompanyStatus.SUSPENDED]: 'Bị khóa',
    [CompanyStatus.DELETED]:   'Ngừng hoạt động',
}

export const VERIFICATION_STATUS_LABELS: Record<VerificationStatus, string> = {
    [VerificationStatus.PENDING]:  'Chờ xác thực',
    [VerificationStatus.VERIFIED]: 'Đã xác thực',
    [VerificationStatus.REJECTED]: 'Bị từ chối',
}


// ─── Mock Data ──────────────────────────────────────────────────────────────────

import type { ResCompanyDTO } from '@/types/company.types'

export const MOCK_COMPANIES: ResCompanyDTO[] = [
    {
        id: 1,
        slug: 'google-viet-nam',
        name: 'Google Việt Nam',
        logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDWf6gBBOkr-u8h4BRVMUMyo7t0Xw6xX1tMcSVM_xVD-R1Ki6rfBo3zq5FqGsAMSl_oal4Qz89y-y4HbWgJxFv64rx6M6uBhjb9-SNf0b7g6EB-AdrsQDM3eE6A_Fn5Gf0igeO4RpjrBwCP3Thlio7D4Wcf0C2GI5vqZZCNs-6xbpWX_5P7Wn66QCFIultVaDunwvw6lw9C1kjtGFD5AZ3XJHcjZBSBIhg7RFU4nVEk6jtvvTz0Zmmp-lDWEs5icDE1RutwrCr0k-5w',
        coverUrl: null,
        description: 'Công ty công nghệ hàng đầu thế giới',
        industryId: 1,
        companySize: CompanySize.ENTERPRISE,
        foundedYear: 1998,
        website: 'https://google.com.vn',
        email: 'contact@google.com.vn',
        phone: '028-1234-5678',
        address: 'Quận 1, TP.HCM',
        provinceId: 1,
        taxCode: '0123456789',
        businessLicenseUrl: null,
        culture: null,
        benefits: '["Bảo hiểm sức khỏe","Thưởng hiệu suất","Đào tạo quốc tế"]',
        socialLinks: null,
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: '2023-05-15T10:00:00Z',
        verifiedBy: 1,
        rejectionReason: null,
        status: CompanyStatus.ACTIVE,
        violationScore: 0,
        suspendedAt: null,
        suspendedReason: null,
        createdBy: 1,
        createdAt: '2023-05-12T08:30:00Z',
        updatedAt: '2023-05-15T10:00:00Z',
    },
    {
        id: 2,
        slug: 'tech-solution-jsc',
        name: 'Tech Solution JSC',
        logoUrl: null,
        coverUrl: null,
        description: 'Công ty giải pháp công nghệ',
        industryId: 1,
        companySize: CompanySize.MEDIUM,
        foundedYear: 2015,
        website: 'https://techsolution.vn',
        email: 'hr@techsolution.vn',
        phone: '028-9876-5432',
        address: 'Quận 7, TP.HCM',
        provinceId: 1,
        taxCode: '9876543210',
        businessLicenseUrl: null,
        culture: null,
        benefits: null,
        socialLinks: null,
        verificationStatus: VerificationStatus.PENDING,
        verifiedAt: null,
        verifiedBy: null,
        rejectionReason: null,
        status: CompanyStatus.PENDING,
        violationScore: 0,
        suspendedAt: null,
        suspendedReason: null,
        createdBy: 2,
        createdAt: '2023-05-15T14:20:00Z',
        updatedAt: '2023-05-15T14:20:00Z',
    },
    {
        id: 3,
        slug: 'meta-inc',
        name: 'Meta Inc.',
        logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkdXYZsGNyz5pj4WOssXYvQnQV9YRpjlJN2Zb6kF5vBpGt1QvN1zUGi1BwAYDMEjBp7wL2hQ1diYIm2AIymGLo-mYIcmZJzLGziQDCTK9R5Mq8O5ohPY7RiLvuIeYpkaPPLDN-e4m9LELtcx8Y6oekSDlNeyWOG1FYSzCku4J4RFdax0drLeeQ_UEU_muZKyND2X0Kr2ShJbzxEWe6tma73aJfL4asM9PSuka2AIHueK_pcjORkEBQnOBHU2SJYOBLjMyGQA4cXvbB',
        coverUrl: null,
        description: 'Mạng xã hội lớn nhất thế giới',
        industryId: 1,
        companySize: CompanySize.ENTERPRISE,
        foundedYear: 2004,
        website: 'https://meta.com',
        email: 'admin@meta.com',
        phone: null,
        address: 'Menlo Park, CA',
        provinceId: null,
        taxCode: null,
        businessLicenseUrl: null,
        culture: null,
        benefits: null,
        socialLinks: null,
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: '2023-04-10T09:00:00Z',
        verifiedBy: 1,
        rejectionReason: null,
        status: CompanyStatus.SUSPENDED,
        violationScore: 3,
        suspendedAt: '2023-06-01T12:00:00Z',
        suspendedReason: 'Vi phạm chính sách tuyển dụng',
        createdBy: 3,
        createdAt: '2023-04-20T07:00:00Z',
        updatedAt: '2023-06-01T12:00:00Z',
    },
    {
        id: 4,
        slug: 'fpt-software',
        name: 'FPT Software',
        logoUrl: null,
        coverUrl: null,
        description: 'Công ty phần mềm hàng đầu Việt Nam',
        industryId: 1,
        companySize: CompanySize.ENTERPRISE,
        foundedYear: 1999,
        website: 'https://fpt-software.com',
        email: 'hr@fpt-software.com',
        phone: '024-7300-7300',
        address: 'Cầu Giấy, Hà Nội',
        provinceId: 2,
        taxCode: '0101234567',
        businessLicenseUrl: null,
        culture: null,
        benefits: '["Bảo hiểm","Du lịch hàng năm","Thưởng tháng 13"]',
        socialLinks: null,
        verificationStatus: VerificationStatus.VERIFIED,
        verifiedAt: '2023-03-20T08:00:00Z',
        verifiedBy: 1,
        rejectionReason: null,
        status: CompanyStatus.ACTIVE,
        violationScore: 0,
        suspendedAt: null,
        suspendedReason: null,
        createdBy: 4,
        createdAt: '2023-03-18T10:00:00Z',
        updatedAt: '2023-03-20T08:00:00Z',
    },
    {
        id: 5,
        slug: 'startup-xyz',
        name: 'Startup XYZ',
        logoUrl: null,
        coverUrl: null,
        description: 'Startup công nghệ mới nổi',
        industryId: 2,
        companySize: CompanySize.SMALL,
        foundedYear: 2023,
        website: 'https://startupxyz.vn',
        email: 'hello@startupxyz.vn',
        phone: '090-1234-567',
        address: 'Quận 3, TP.HCM',
        provinceId: 1,
        taxCode: null,
        businessLicenseUrl: null,
        culture: null,
        benefits: null,
        socialLinks: null,
        verificationStatus: VerificationStatus.REJECTED,
        verifiedAt: null,
        verifiedBy: 1,
        rejectionReason: 'Thiếu giấy phép kinh doanh',
        status: CompanyStatus.PENDING,
        violationScore: 0,
        suspendedAt: null,
        suspendedReason: null,
        createdBy: 5,
        createdAt: '2023-06-01T09:00:00Z',
        updatedAt: '2023-06-02T14:00:00Z',
    },
]